# Question 1 (10 Marks)
## Write a Python program with the following requirements:
## 1.Create a function that reads the Employee Database CSV file and returns a Pandas DataFrame with proper error handling for file operations
### Uses try-except-finally block to ensure resources are properly managed
### Handles FileNotFoundError with meaningful error messages

In [6]:
import numpy as np
import pandas as pd

In [7]:
df=pd.read_csv('employee_database(in).csv')
df

,EmployeeID,FirstName,LastName,Department,Designation,JoiningDate,Salary,Age,YearsOfExperience,Performance_Rating,Project_Count
0,1001,Arjun,Verma,Sales,Software Engineer,5/27/2016,1470473,50,1,3.57,14
1,1002,Sneha,Reddy,Sales,Software Engineer,9/15/2021,820082,26,10,3.35,11
2,1003,Rohan,Desai,Finance,Senior Manager,3/14/2021,1343361,28,25,4.58,1
3,1004,Divya,Sharma,Engineering,Manager,6/2/2022,2480943,57,6,3.61,4
4,1005,Vikram,Desai,Finance,Data Analyst,9/12/2016,2028235,48,5,2.40,2
...,...,...,...,...,...,...,...,...,...,...,...
1195,2196,Kavya,Patel,Engineering,Associate,12/18/2020,321576,39,23,4.74,8
1196,2197,Sneha,Verma,Finance,Associate,2/5/2023,1335865,39,5,1.35,13
1197,2198,Sneha,Gupta,Finance,Executive,4/18/2019,1628668,45,24,4.20,3
1198,2199,Vikram,Gupta,Finance,Data Analyst,6/29/2022,2486203,23,0,4.59,1
1199,2200,Divya,Verma,HR,Senior Manager,2/15/2024,2332342,41,24,4.76,9

In [48]:
def Employee(df):
    if df not in employee_databse.csv:
        print("File not Found please upload the proper filey")
    else:
        print("File uploade sucessfully")

In [49]:
e=Employee(df)

NameError: name 'employee_databse' is not defined

In [50]:
try:
    data=employee_database.csv
    print("Uploaded correct file")
except FileNotFoundError: 
    print("Please Upload the Correct File Name")
finally:
    print("DataFrame Successful")

DataFrame Successful

AttributeError: 'function' object has no attribute 'csv'

In [8]:
#Exact Answer
def read_database(employee_database):
    try:
        df=pd.read_csv("employee_database(in).csv")
        print("File Uploaded Successfully")
        return df
    except FileNotFoundError:
        print(f"The File employee_database(in).csv was not found.Please check the File Path")
    finally:
        print("File Uploaded Completed")

In [9]:
r=read_database("employee_database(in).csv")

File Uploaded Successfully
File Uploaded Completed

## 2.Create a custom exception class and a function that extracts employee information by ID
### Implements custom exception if employee ID doesn't exist
### Returns a formatted string: "FirstName LastName works in Department as Designation"
### Uses try-except block to catch and raise this custom exception

In [10]:
#Exact Answers
class EmployeeNotFoundError(Exception):
    pass

def get_employee_info_by_id(df, emp_id):
    try:
        row = df[df['EmployeeID'] == emp_id]

        if row.empty:
            raise EmployeeNotFoundError("Employee ID not found")

        row = row.iloc[0]
        return f"{row['FirstName']} {row['LastName']} works in {row['Department']} as {row['Designation']}"

    except EmployeeNotFoundError:
        raise

## 3.Main execution:
### Load the employee database
### Extract and display information for Employee ID 1050
### Demonstrate exception handling by attempting to fetch a non-existent Employee ID
### Dataset: employee_database.csv

In [51]:
import numpy as np
import pandas as pd
df=pd.read_csv('employee_database(in).csv')
df

,EmployeeID,FirstName,LastName,Department,Designation,JoiningDate,Salary,Age,YearsOfExperience,Performance_Rating,Project_Count
0,1001,Arjun,Verma,Sales,Software Engineer,5/27/2016,1470473,50,1,3.57,14
1,1002,Sneha,Reddy,Sales,Software Engineer,9/15/2021,820082,26,10,3.35,11
2,1003,Rohan,Desai,Finance,Senior Manager,3/14/2021,1343361,28,25,4.58,1
3,1004,Divya,Sharma,Engineering,Manager,6/2/2022,2480943,57,6,3.61,4
4,1005,Vikram,Desai,Finance,Data Analyst,9/12/2016,2028235,48,5,2.40,2
...,...,...,...,...,...,...,...,...,...,...,...
1195,2196,Kavya,Patel,Engineering,Associate,12/18/2020,321576,39,23,4.74,8
1196,2197,Sneha,Verma,Finance,Associate,2/5/2023,1335865,39,5,1.35,13
1197,2198,Sneha,Gupta,Finance,Executive,4/18/2019,1628668,45,24,4.20,3
1198,2199,Vikram,Gupta,Finance,Data Analyst,6/29/2022,2486203,23,0,4.59,1
1199,2200,Divya,Verma,HR,Senior Manager,2/15/2024,2332342,41,24,4.76,9

In [232]:
filter=df[df['EmployeeID']=='1050']
filter.info()
filter

<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 11 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   EmployeeID          0 non-null      int64
 1   FirstName           0 non-null      object
 2   LastName            0 non-null      object
 3   Department          0 non-null      object
 4   Designation         0 non-null      object
 5   JoiningDate         0 non-null      object
 6   Salary              0 non-null      int64
 7   Age                 0 non-null      int64
 8   YearsOfExperience   0 non-null      int64
 9   Performance_Rating  0 non-null      float64
 10  Project_Count       0 non-null      int64
dtypes: float64(1), int64(5), object(5)
memory usage: 0.0+ bytes

Empty DataFrame
Columns: [EmployeeID, FirstName, LastName, Department, Designation, JoiningDate, Salary, Age, YearsOfExperience, Performance_Rating, Project_Count]
Index: []

In [61]:
def Emp(df):
    try:
        print("EmployeeID is present in dataset")
    except ValueError:
        print("please Give me proper employee ID")
    finally:
        print("Successful")
e=Emp(df[df['EmployeeID']=='2500'])
e

EmployeeID is present in dataset
Successful

In [11]:
# for this question answer in ExactAnswers.ipynb file

# Question 2 (10 Marks)
## Write a Python program with the following requirements:
## 1.Create a function that:
### Validates name fields in a DataFrame
### Combines first and last names using string concatenation
### Uses if-elif-else to categorize based on:
### Name length > 15 characters: "Long Name"
### Contains numbers: "Invalid Format"
### Otherwise: "Valid"
### Returns tuples with ID, full name, and status

In [68]:
filter=df[df['EmployeeName']=='verma']
filter

KeyError: 'EmployeeName'

In [233]:
df['Employeename']=df['FirstName'] + df['LastName']
df

,EmployeeID,FirstName,LastName,Department,Designation,JoiningDate,Salary,Age,YearsOfExperience,Performance_Rating,Project_Count,Employeename
0,1001,Arjun,Verma,Sales,Software Engineer,5/27/2016,1470473,50,1,3.57,14,ArjunVerma
1,1002,Sneha,Reddy,Sales,Software Engineer,9/15/2021,820082,26,10,3.35,11,SnehaReddy
2,1003,Rohan,Desai,Finance,Senior Manager,3/14/2021,1343361,28,25,4.58,1,RohanDesai
3,1004,Divya,Sharma,Engineering,Manager,6/2/2022,2480943,57,6,3.61,4,DivyaSharma
4,1005,Vikram,Desai,Finance,Data Analyst,9/12/2016,2028235,48,5,2.40,2,VikramDesai
...,...,...,...,...,...,...,...,...,...,...,...,...
1195,2196,Kavya,Patel,Engineering,Associate,12/18/2020,321576,39,23,4.74,8,KavyaPatel
1196,2197,Sneha,Verma,Finance,Associate,2/5/2023,1335865,39,5,1.35,13,SnehaVerma
1197,2198,Sneha,Gupta,Finance,Executive,4/18/2019,1628668,45,24,4.20,3,SnehaGupta
1198,2199,Vikram,Gupta,Finance,Data Analyst,6/29/2022,2486203,23,0,4.59,1,VikramGupta
1199,2200,Divya,Verma,HR,Senior Manager,2/15/2024,2332342,41,24,4.76,9,DivyaVerma

In [74]:
def emp_database(df):
    if len(df['Employeename'])>15:
        print("Long Name")
    elif len(df['Employeename'])<=15:
        print("Invalid Format")
    else:
        print("Valid")
e2=emp_database(df[df['Employeename']=='DivyaVerma'])

Invalid Format

In [12]:
#Exact Answers
def validate_names(df):
    result=[]
    for i,row in df.iterrows():
        emp_id=row['EmployeeID']
        first_name=str(row['FirstName'])
        last_name=str(row['LastName'])
        full_name=first_name+ " "+last_name
        if len(full_name)>15:
            status="Long Name"
        elif any(char.isdigit() for char in full_name):
            status="Invalid Format"
        else:
            status="Valid"
    result.append((emp_id, full_name, status))
    return pd.DataFrame(result, columns=['EmployeeID', 'FullName', 'Status'])

In [13]:
df2=validate_names(df)
print(df2)

   EmployeeID     FullName Status
0        2200  Divya Verma  Valid

## 2.Create a function that:
### Uses string methods (startswith, endswith, find) to filter names
### Accepts a pattern parameter
### Returns matching employees using list comprehension

In [14]:
#Exact Answer
def filter_name(df,pattern,method='find'):
    df['FullName'] = df['FirstName'] + " " + df['LastName']
    if method=='startswith':
        filter=df[df['FullName'].str.startswith(pattern)]
    elif method=='endswith':
        filter=df[df['FullName'].str.endswith(pattern)]
    elif method=='find':
        filter=df[df['FullName'].str.contains(pattern)]
    else:
        raise ValueError("Method must be 'startswith','endswith','find'")
    return list(zip(filter['EmployeeID'],filter['FullName']))

In [15]:
print("Starts with 'A':", filter_name(df, 'Am', 'startswith'))
print("Ends with 'ir':", filter_name(df, 'ir', 'endswith'))
print("Contains 'ha':", filter_name(df, 'ha', 'find'))

Starts with 'A': [(1008, 'Amit Kumar'), (1017, 'Amit Singh'), (1039, 'Amit Desai'), (1044, 'Amit Patel'), (1046, 'Amit Kumar'), (1067, 'Amit Singh'), (1110, 'Amit Kumar'), (1113, 'Amit Reddy'), (1114, 'Amit Gupta'), (1133, 'Amit Desai'), (1138, 'Amit Kumar'), (1140, 'Amit Singh'), (1142, 'Amit Patel'), (1153, 'Amit Verma'), (1165, 'Amit Reddy'), (1191, 'Amit Gupta'), (1199, 'Amit Verma'), (1215, 'Amit Patel'), (1231, 'Amit Patel'), (1257, 'Amit Reddy'), (1262, 'Amit Kumar'), (1264, 'Amit Verma'), (1265, 'Amit Kumar'), (1283, 'Amit Gupta'), (1300, 'Amit Rao'), (1301, 'Amit Verma'), (1302, 'Amit Rao'), (1317, 'Amit Kumar'), (1319, 'Amit Kumar'), (1325, 'Amit Rao'), (1336, 'Amit Kumar'), (1341, 'Amit Kumar'), (1347, 'Amit Reddy'), (1359, 'Amit Singh'), (1361, 'Amit Verma'), (1368, 'Amit Reddy'), (1375, 'Amit Reddy'), (1382, 'Amit Reddy'), (1388, 'Amit Patel'), (1409, 'Amit Patel'), (1422, 'Amit Nair'), (1429, 'Amit Desai'), (1455, 'Amit Gupta'), (1462, 'Amit Verma'), (1465, 'Amit Gupta'), (1491, 'Amit Desai'), (1494, 'Amit Verma'), (1521, 'Amit Desai'), (1537, 'Amit Verma'), (1541, 'Amit Kumar'), (1545, 'Amit Sharma'), (1554, 'Amit Reddy'), (1556, 'Amit Sharma'), (1565, 'Amit Desai'), (1583, 'Amit Sharma'), (1585, 'Amit Verma'), (1598, 'Amit Sharma'), (1606, 'Amit Patel'), (1611, 'Amit Nair'), (1617, 'Amit Patel'), (1621, 'Amit Desai'), (1638, 'Amit Patel'), (1661, 'Amit Verma'), (1673, 'Amit Desai'), (1680, 'Amit Verma'), (1682, 'Amit Reddy'), (1692, 'Amit Singh'), (1712, 'Amit Kumar'), (1713, 'Amit Desai'), (1723, 'Amit Nair'), (1757, 'Amit Singh'), (1760, 'Amit Verma'), (1787, 'Amit Patel'), (1797, 'Amit Gupta'), (1805, 'Amit Patel'), (1810, 'Amit Gupta'), (1824, 'Amit Reddy'), (1840, 'Amit Sharma'), (1850, 'Amit Gupta'), (1860, 'Amit Gupta'), (1880, 'Amit Nair'), (1892, 'Amit Verma'), (1893, 'Amit Singh'), (1897, 'Amit Verma'), (1898, 'Amit Rao'), (1929, 'Amit Desai'), (1941, 'Amit Gupta'), (1943, 'Amit Verma'), (1950, 'Amit Desai'), (1951, 'Amit Nair'), (1970, 'Amit Sharma'), (1980, 'Amit Sharma'), (2007, 'Amit Rao'), (2008, 'Amit Singh'), (2024, 'Amit Verma'), (2030, 'Amit Gupta'), (2037, 'Amit Patel'), (2050, 'Amit Rao'), (2073, 'Amit Reddy'), (2085, 'Amit Nair'), (2086, 'Amit Verma'), (2096, 'Amit Patel'), (2100, 'Amit Gupta'), (2112, 'Amit Gupta'), (2125, 'Amit Desai'), (2127, 'Amit Patel'), (2130, 'Amit Sharma'), (2132, 'Amit Sharma'), (2168, 'Amit Verma'), (2169, 'Amit Nair')]
Ends with 'ir': [(1006, 'Arjun Nair'), (1010, 'Rohan Nair'), (1020, 'Priya Nair'), (1027, 'Rajesh Nair'), (1029, 'Pooja Nair'), (1032, 'Nikhil Nair'), (1035, 'Rohan Nair'), (1038, 'Kavya Nair'), (1049, 'Nikhil Nair'), (1065, 'Kavya Nair'), (1108, 'Divya Nair'), (1115, 'Rajesh Nair'), (1155, 'Rajesh Nair'), (1171, 'Vikram Nair'), (1174, 'Kavya Nair'), (1176, 'Kavya Nair'), (1190, 'Nikhil Nair'), (1195, 'Rohan Nair'), (1203, 'Rohan Nair'), (1207, 'Sneha Nair'), (1247, 'Sneha Nair'), (1251, 'Rohan Nair'), (1252, 'Rajesh Nair'), (1256, 'Ananya Nair'), (1259, 'Kavya Nair'), (1273, 'Priya Nair'), (1286, 'Pooja Nair'), (1288, 'Sneha Nair'), (1290, 'Rajesh Nair'), (1303, 'Sneha Nair'), (1330, 'Rajesh Nair'), (1346, 'Ananya Nair'), (1348, 'Ananya Nair'), (1350, 'Rohan Nair'), (1362, 'Rajesh Nair'), (1365, 'Kavya Nair'), (1367, 'Ananya Nair'), (1378, 'Sneha Nair'), (1389, 'Divya Nair'), (1391, 'Priya Nair'), (1402, 'Nikhil Nair'), (1417, 'Sneha Nair'), (1418, 'Sneha Nair'), (1422, 'Amit Nair'), (1425, 'Priya Nair'), (1427, 'Arjun Nair'), (1430, 'Nikhil Nair'), (1432, 'Ananya Nair'), (1460, 'Kavya Nair'), (1461, 'Pooja Nair'), (1469, 'Pooja Nair'), (1482, 'Ananya Nair'), (1492, 'Kavya Nair'), (1527, 'Divya Nair'), (1542, 'Rohan Nair'), (1551, 'Kavya Nair'), (1555, 'Priya Nair'), (1568, 'Sneha Nair'), (1573, 'Divya Nair'), (1575, 'Nikhil Nair'), (1589, 'Arjun Nair'), (1592, 'Vikram Nair'), (1597, 'Nikhil Nair'), (1599, 'Nikhil Nair'), (1611, 'Amit Nair'), (1630, 'Nikhil Nair'), (1632, 'Vikram Nair'), (1634, 'Pooja Nair'), (1648, 'Rajesh Nair'), (1653, 'Nikhil Nair'), (1671, 'Ananya Nair'), (1691, 'Rajesh Nair'), (1723, 'Amit Nair'), (1727, 'Kavya Nair'), (1733, 'Kavya Nair'), (1734, 'Vikram Nair'), (1749, 'Rohan Nair'), (1755, 'Sneha Nair'), (1758, 'Ananya Nair'), (1770, 'Divya Nair'), (1790, 'Arjun Nair'), (1792, 'Kavya Nair'), (1827, 'Kavya Nair'), (1834, 'Rajesh Nair'), (1839, 'Rohan Nair'), (1841, 'Arjun Nair'), (1842, 'Ananya Nair'), (1843, 'Kavya Nair'), (1845, 'Ananya Nair'), (1855, 'Rajesh Nair'), (1862, 'Vikram Nair'), (1869, 'Kavya Nair'), (1880, 'Amit Nair'), (1889, 'Sneha Nair'), (1901, 'Priya Nair'), (1921, 'Divya Nair'), (1945, 'Rohan Nair'), (1947, 'Priya Nair'), (1951, 'Amit Nair'), (1965, 'Rajesh Nair'), (1986, 'Pooja Nair'), (1987, 'Priya Nair'), (1988, 'Rohan Nair'), (1998, 'Ananya Nair'), (2014, 'Priya Nair'), (2018, 'Sneha Nair'), (2049, 'Rohan Nair'), (2052, 'Ananya Nair'), (2067, 'Rajesh Nair'), (2085, 'Amit Nair'), (2088, 'Divya Nair'), (2089, 'Ananya Nair'), (2116, 'Rajesh Nair'), (2126, 'Arjun Nair'), (2128, 'Ananya Nair'), (2137, 'Sneha Nair'), (2139, 'Rohan Nair'), (2146, 'Arjun Nair'), (2159, 'Divya Nair'), (2163, 'Vikram Nair'), (2166, 'Priya Nair'), (2169, 'Amit Nair')]
Contains 'ha': [(1002, 'Sneha Reddy'), (1003, 'Rohan Desai'), (1004, 'Divya Sharma'), (1010, 'Rohan Nair'), (1011, 'Rohan Gupta'), (1013, 'Vikram Sharma'), (1014, 'Sneha Verma'), (1021, 'Divya Sharma'), (1034, 'Rohan Desai'), (1035, 'Rohan Nair'), (1042, 'Sneha Rao'), (1045, 'Vikram Sharma'), (1052, 'Sneha Gupta'), (1055, 'Priya Sharma'), (1056, 'Pooja Sharma'), (1061, 'Sneha Sharma'), (1063, 'Kavya Sharma'), (1066, 'Divya Sharma'), (1069, 'Sneha Gupta'), (1071, 'Divya Sharma'), (1072, 'Sneha Rao'), (1073, 'Priya Sharma'), (1077, 'Sneha Kumar'), (1078, 'Ananya Sharma'), (1082, 'Priya Sharma'), (1084, 'Sneha Patel'), (1087, 'Kavya Sharma'), (1092, 'Vikram Sharma'), (1101, 'Nikhil Sharma'), (1107, 'Divya Sharma'), (1109, 'Rohan Rao'), (1116, 'Rohan Verma'), (1119, 'Arjun Sharma'), (1135, 'Divya Sharma'), (1137, 'Rohan Verma'), (1143, 'Rajesh Sharma'), (1148, 'Rohan Kumar'), (1156, 'Sneha Patel'), (1157, 'Sneha Verma'), (1161, 'Rohan Gupta'), (1162, 'Sneha Reddy'), (1163, 'Arjun Sharma'), (1164, 'Rohan Desai'), (1167, 'Kavya Sharma'), (1170, 'Nikhil Sharma'), (1177, 'Sneha Gupta'), (1178, 'Rohan Gupta'), (1187, 'Rohan Verma'), (1189, 'Sneha Singh'), (1193, 'Ananya Sharma'), (1195, 'Rohan Nair'), (1203, 'Rohan Nair'), (1207, 'Sneha Nair'), (1211, 'Sneha Sharma'), (1217, 'Vikram Sharma'), (1221, 'Rohan Kumar'), (1226, 'Ananya Sharma'), (1238, 'Sneha Sharma'), (1240, 'Rohan Singh'), (1242, 'Rohan Kumar'), (1245, 'Divya Sharma'), (1247, 'Sneha Nair'), (1251, 'Rohan Nair'), (1254, 'Kavya Sharma'), (1255, 'Rohan Sharma'), (1258, 'Sneha Desai'), (1260, 'Rohan Rao'), (1261, 'Sneha Kumar'), (1266, 'Sneha Gupta'), (1268, 'Sneha Kumar'), (1270, 'Rajesh Sharma'), (1271, 'Divya Sharma'), (1275, 'Rajesh Sharma'), (1276, 'Rohan Reddy'), (1280, 'Priya Sharma'), (1288, 'Sneha Nair'), (1294, 'Vikram Sharma'), (1296, 'Rohan Desai'), (1303, 'Sneha Nair'), (1309, 'Sneha Singh'), (1310, 'Rohan Rao'), (1313, 'Sneha Desai'), (1315, 'Divya Sharma'), (1316, 'Sneha Reddy'), (1327, 'Sneha Sharma'), (1329, 'Sneha Gupta'), (1332, 'Sneha Sharma'), (1340, 'Rohan Patel'), (1344, 'Ananya Sharma'), (1350, 'Rohan Nair'), (1351, 'Rohan Rao'), (1354, 'Rajesh Sharma'), (1355, 'Kavya Sharma'), (1360, 'Sneha Patel'), (1363, 'Rajesh Sharma'), (1366, 'Vikram Sharma'), (1378, 'Sneha Nair'), (1392, 'Ananya Sharma'), (1395, 'Rohan Reddy'), (1401, 'Rajesh Sharma'), (1403, 'Rohan Kumar'), (1406, 'Pooja Sharma'), (1411, 'Nikhil Sharma'), (1417, 'Sneha Nair'), (1418, 'Sneha Nair'), (1437, 'Sneha Reddy'), (1441, 'Rohan Gupta'), (1444, 'Rajesh Sharma'), (1452, 'Sneha Patel'), (1454, 'Sneha Sharma'), (1458, 'Sneha Reddy'), (1459, 'Priya Sharma'), (1481, 'Priya Sharma'), (1483, 'Nikhil Sharma'), (1501, 'Sneha Sharma'), (1503, 'Kavya Sharma'), (1506, 'Vikram Sharma'), (1508, 'Sneha Desai'), (1516, 'Sneha Sharma'), (1518, 'Sneha Kumar'), (1525, 'Vikram Sharma'), (1526, 'Sneha Kumar'), (1532, 'Rohan Singh'), (1533, 'Sneha Gupta'), (1535, 'Kavya Sharma'), (1542, 'Rohan Nair'), (1545, 'Amit Sharma'), (1550, 'Rohan Sharma'), (1556, 'Amit Sharma'), (1568, 'Sneha Nair'), (1570, 'Vikram Sharma'), (1572, 'Rohan Singh'), (1574, 'Sneha Gupta'), (1578, 'Sneha Verma'), (1583, 'Amit Sharma'), (1586, 'Sneha Patel'), (1590, 'Divya Sharma'), (1598, 'Amit Sharma'), (1602, 'Sneha Singh'), (1603, 'Nikhil Sharma'), (1605, 'Rohan Reddy'), (1607, 'Rajesh Sharma'), (1608, 'Sneha Patel'), (1609, 'Kavya Sharma'), (1610, 'Nikhil Sharma'), (1612, 'Kavya Sharma'), (1616, 'Sneha Rao'), (1624, 'Sneha Desai'), (1625, 'Rohan Rao'), (1626, 'Vikram Sharma'), (1627, 'Sneha Reddy'), (1640, 'Rohan Rao'), (1641, 'Rohan Singh'), (1655, 'Rohan Desai'), (1665, 'Sneha Gupta'), (1669, 'Sneha Verma'), (1670, 'Sneha Reddy'), (1677, 'Rohan Sharma'), (1679, 'Pooja Sharma'), (1686, 'Sneha Singh'), (1689, 'Nikhil Sharma'), (1708, 'Rohan Patel'), (1711, 'Sneha Sharma'), (1714, 'Sneha Reddy'), (1726, 'Rohan Rao'), (1732, 'Divya Sharma'), (1738, 'Sneha Verma'), (1739, 'Pooja Sharma'), (1748, 'Sneha Desai'), (1749, 'Rohan Nair'), (1750, 'Ananya Sharma'), (1754, 'Vikram Sharma'), (1755, 'Sneha Nair'), (1762, 'Nikhil Sharma'), (1763, 'Priya Sharma'), (1767, 'Rohan Singh'), (1774, 'Priya Sharma'), (1776, 'Rohan Kumar'), (1781, 'Rohan Sharma'), (1782, 'Rohan Sharma'), (1807, 'Vikram Sharma'), (1811, 'Sneha Verma'), (1814, 'Divya Sharma'), (1821, 'Priya Sharma'), (1825, 'Rohan Sharma'), (1829, 'Ananya Sharma'), (1830, 'Kavya Sharma'), (1832, 'Rohan Verma'), (1839, 'Rohan Nair'), (1840, 'Amit Sharma'), (1849, 'Rohan Singh'), (1852, 'Sneha Gupta'), (1858, 'Arjun Sharma'), (1863, 'Sneha Verma'), (1864, 'Pooja Sharma'), (1870, 'Sneha Sharma'), (1871, 'Divya Sharma'), (1872, 'Vikram Sharma'), (1877, 'Rohan Reddy'), (1878, 'Rohan Desai'), (1879, 'Rohan Patel'), (1884, 'Rohan Reddy'), (1887, 'Sneha Verma'), (1889, 'Sneha Nair'), (1894, 'Rohan Rao'), (1915, 'Rohan Singh'), (1918, 'Nikhil Sharma'), (1922, 'Rohan Rao'), (1925, 'Sneha Rao'), (1927, 'Divya Sharma'), (1930, 'Sneha Reddy'), (1937, 'Priya Sharma'), (1939, 'Rohan Desai'), (1945, 'Rohan Nair'), (1955, 'Kavya Sharma'), (1966, 'Sneha Patel'), (1968, 'Sneha Singh'), (1970, 'Amit Sharma'), (1973, 'Sneha Verma'), (1974, 'Ananya Sharma'), (1977, 'Divya Sharma'), (1980, 'Amit Sharma'), (1985, 'Sneha Desai'), (1988, 'Rohan Nair'), (1990, 'Rohan Kumar'), (1999, 'Ananya Sharma'), (2001, 'Sneha Reddy'), (2002, 'Rohan Kumar'), (2011, 'Sneha Sharma'), (2015, 'Sneha Reddy'), (2016, 'Kavya Sharma'), (2017, 'Rohan Gupta'), (2018, 'Sneha Nair'), (2021, 'Rajesh Sharma'), (2027, 'Rohan Reddy'), (2036, 'Sneha Rao'), (2038, 'Sneha Gupta'), (2039, 'Rajesh Sharma'), (2040, 'Sneha Kumar'), (2047, 'Rohan Singh'), (2048, 'Sneha Verma'), (2049, 'Rohan Nair'), (2054, 'Divya Sharma'), (2063, 'Sneha Singh'), (2066, 'Nikhil Sharma'), (2069, 'Rohan Singh'), (2075, 'Vikram Sharma'), (2081, 'Rohan Sharma'), (2090, 'Kavya Sharma'), (2092, 'Rohan Singh'), (2101, 'Rohan Gupta'), (2103, 'Sneha Singh'), (2105, 'Pooja Sharma'), (2130, 'Amit Sharma'), (2132, 'Amit Sharma'), (2135, 'Sneha Kumar'), (2137, 'Sneha Nair'), (2139, 'Rohan Nair'), (2140, 'Sneha Verma'), (2145, 'Rohan Singh'), (2148, 'Sneha Singh'), (2153, 'Rohan Kumar'), (2158, 'Sneha Desai'), (2160, 'Sneha Patel'), (2164, 'Sneha Rao'), (2167, 'Rohan Kumar'), (2170, 'Sneha Kumar'), (2171, 'Sneha Rao'), (2172, 'Pooja Sharma'), (2173, 'Rohan Singh'), (2174, 'Rohan Singh'), (2176, 'Sneha Reddy'), (2177, 'Rohan Sharma'), (2185, 'Rohan Patel'), (2194, 'Rohan Verma'), (2197, 'Sneha Verma'), (2198, 'Sneha Gupta')]

## 3. Main execution:
### Process all employee names
### Filter by specific name patterns
### Display validation counts using dictionaries
### Dataset: employee_database.csv

In [16]:
# for this question answer in ExactAnswers.ipynb file

## Question 3 (10 Marks)
## Write a Python program with the following requirements:
### 1.Create a class that accepts a Pandas DataFrame in its constructor

In [95]:
class Employee:
    def __init__(self,df):
        self.df=df
    def show(df):
        print(df)
e5=Employee
e5.show(df)

      EmployeeID FirstName LastName   Department        Designation  \
0           1001     Arjun    Verma        Sales  Software Engineer
1           1002     Sneha    Reddy        Sales  Software Engineer
2           1003     Rohan    Desai      Finance     Senior Manager
3           1004     Divya   Sharma  Engineering            Manager
4           1005    Vikram    Desai      Finance       Data Analyst
...          ...       ...      ...          ...                ...
1195        2196     Kavya    Patel  Engineering          Associate
1196        2197     Sneha    Verma      Finance          Associate
1197        2198     Sneha    Gupta      Finance          Executive
1198        2199    Vikram    Gupta      Finance       Data Analyst
1199        2200     Divya    Verma           HR     Senior Manager

     JoiningDate   Salary  Age  YearsOfExperience  Performance_Rating  \
0      5/27/2016  1470473   50                  1                3.57
1      9/15/2021   820082   26                 10                3.35
2      3/14/2021  1343361   28                 25                4.58
3       6/2/2022  2480943   57                  6                3.61
4      9/12/2016  2028235   48                  5                2.40
...          ...      ...  ...                ...                 ...
1195  12/18/2020   321576   39                 23                4.74
1196    2/5/2023  1335865   39                  5                1.35
1197   4/18/2019  1628668   45                 24                4.20
1198   6/29/2022  2486203   23                  0                4.59
1199   2/15/2024  2332342   41                 24                4.76

      Project_Count Employeename
0                14   ArjunVerma
1                11   SnehaReddy
2                 1   RohanDesai
3                 4  DivyaSharma
4                 2  VikramDesai
...             ...          ...
1195              8   KavyaPatel
1196             13   SnehaVerma
1197              3   SnehaGupta
1198              1  VikramGupta
1199              9   DivyaVerma

[1200 rows x 12 columns]

### 2.Implement methods that:
#### Return a dictionary with department names as keys and values containing total employees,average salary, and average performance rating
#### Return a dictionary with department names as keys and highest-paid employee names as values

In [128]:
df['total_emp']=df['EmployeeID'].count()

In [114]:
df['avg_sal']=df['Salary'].mean().round(2)

In [126]:
df['performance']=df['Performance_Rating'].mean().round(2)

In [137]:
best=df['Salary'].max()
best

2494358

In [129]:
df

,EmployeeID,FirstName,LastName,Department,Designation,JoiningDate,Salary,Age,YearsOfExperience,Performance_Rating,Project_Count,Employeename,total_emp,avg_sal,performance
0,1001,Arjun,Verma,Sales,Software Engineer,5/27/2016,1470473,50,1,3.57,14,ArjunVerma,1200,1396182.55,3.04
1,1002,Sneha,Reddy,Sales,Software Engineer,9/15/2021,820082,26,10,3.35,11,SnehaReddy,1200,1396182.55,3.04
2,1003,Rohan,Desai,Finance,Senior Manager,3/14/2021,1343361,28,25,4.58,1,RohanDesai,1200,1396182.55,3.04
3,1004,Divya,Sharma,Engineering,Manager,6/2/2022,2480943,57,6,3.61,4,DivyaSharma,1200,1396182.55,3.04
4,1005,Vikram,Desai,Finance,Data Analyst,9/12/2016,2028235,48,5,2.40,2,VikramDesai,1200,1396182.55,3.04
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1195,2196,Kavya,Patel,Engineering,Associate,12/18/2020,321576,39,23,4.74,8,KavyaPatel,1200,1396182.55,3.04
1196,2197,Sneha,Verma,Finance,Associate,2/5/2023,1335865,39,5,1.35,13,SnehaVerma,1200,1396182.55,3.04
1197,2198,Sneha,Gupta,Finance,Executive,4/18/2019,1628668,45,24,4.20,3,SnehaGupta,1200,1396182.55,3.04
1198,2199,Vikram,Gupta,Finance,Data Analyst,6/29/2022,2486203,23,0,4.59,1,VikramGupta,1200,1396182.55,3.04
1199,2200,Divya,Verma,HR,Senior Manager,2/15/2024,2332342,41,24,4.76,9,DivyaVerma,1200,1396182.55,3.04

In [ ]:
# for this question answer in ExactAnswers.ipynb file

### 3.Use NumPy for numerical calculations (mean operations)

In [218]:
arr=df.to_numpy()
arr

array([[1001, 'Arjun', 'Verma', ..., 1, 3.57, 14],
       [1002, 'Sneha', 'Reddy', ..., 10, 3.35, 11],
       [1003, 'Rohan', 'Desai', ..., 25, 4.58, 1],
       ...,
       [2198, 'Sneha', 'Gupta', ..., 24, 4.2, 3],
       [2199, 'Vikram', 'Gupta', ..., 0, 4.59, 1],
       [2200, 'Divya', 'Verma', ..., 24, 4.76, 9]], dtype=object)

In [17]:
# for this question answer in ExactAnswers.ipynb file

### 4. Main execution:
#### Instantiate the class with employee data
#### Display results from both methods
#### Dataset: employee_database.csv

In [18]:
# for this question answer in ExactAnswers.ipynb file

## Question 4 (10 Marks)
## Write a Python program with the following requirements:
### 1. Load employee data and create NumPy arrays for:
### Salary data
### Years of experience
### Employee age

In [162]:
arr=np.array(df['Salary'],df['YearsOfExperience'],df['Age'])
arr

AttributeError: 'numpy.float64' object has no attribute 'array'

### 2.Perform NumPy operations:
### Calculate mean, median, standard deviation, minimum, and maximum for salaries
### Create a normalized salary array using (x - min)/(max - min) formula
### Use np.digitize() to create salary brackets:
### Bracket 1: < 500K
### Bracket 2: 500K-1M
### Bracket 3: 1M-1.5M
### Bracket 4: > 1.5M

In [224]:
df

,EmployeeID,FirstName,LastName,Department,Designation,JoiningDate,Salary,Age,YearsOfExperience,Performance_Rating,Project_Count
0,1001,Arjun,Verma,Sales,Software Engineer,5/27/2016,1470473,50,1,3.57,14
1,1002,Sneha,Reddy,Sales,Software Engineer,9/15/2021,820082,26,10,3.35,11
2,1003,Rohan,Desai,Finance,Senior Manager,3/14/2021,1343361,28,25,4.58,1
3,1004,Divya,Sharma,Engineering,Manager,6/2/2022,2480943,57,6,3.61,4
4,1005,Vikram,Desai,Finance,Data Analyst,9/12/2016,2028235,48,5,2.40,2
...,...,...,...,...,...,...,...,...,...,...,...
1195,2196,Kavya,Patel,Engineering,Associate,12/18/2020,321576,39,23,4.74,8
1196,2197,Sneha,Verma,Finance,Associate,2/5/2023,1335865,39,5,1.35,13
1197,2198,Sneha,Gupta,Finance,Executive,4/18/2019,1628668,45,24,4.20,3
1198,2199,Vikram,Gupta,Finance,Data Analyst,6/29/2022,2486203,23,0,4.59,1
1199,2200,Divya,Verma,HR,Senior Manager,2/15/2024,2332342,41,24,4.76,9

In [222]:
mean=df['Salary'].mean()
mean

np.float64(1396182.5541666667)

In [172]:
median=df['Salary'].median()
median

1365412.5

In [175]:
min=df['Salary'].min()
min

300215

In [227]:
max=df['Salary'].max()
max

2494358

In [228]:
norm=df-np.min(salary)/np.max(salary)-np.min(salary)
norm

NameError: name 'salary' is not defined

In [226]:
salary_bracket=np.digitize(if(salary <50000):print("Bracket1")
                           elif(salary>50000 and salary<=100000):print("Bracket2")
                           elif(salary>100000 and salary<=150000):print("Bracket3")
                           else:print("Bracket4"))

SyntaxError: invalid syntax (19560078.py, line 2)

## 3.Create a function that:
### Calculates correlation between two arrays using NumPy
### Returns comprehensive statistical measures as a dictionary
### Uses NumPy broadcasting for vectorized operations
## 4. Error handling:
### Validate array dimensions
### Handle division by zero scenarios
## 5.Main execution:
### Display all salary statistics
### Show bracket distribution using np.bincount
### Display correlation analysis

## Question 5 (10 Marks)
### Write a Python program with the following requirements:
### 1. Create a base class with:
### Private attributes using name mangling
### Public accessor methods
### A protected method that calculates a 10% bonus

In [193]:
class Student(df):
    def __init__(self,name,salary,bonus):
        self.__name=name
        self.salary=salary
        self._bonus=bonus
    def bonus(self):
        return self._bonus*1.01

### 2. Create two derived classes that:
### Inherit from the base class
### Have additional specific attributes
### Override the bonus calculation method (15% and 12% respectively)
### Include role-specific methods

In [195]:
class Friends(Student):
    def bonus(self):
        return self._bonus*1.15

In [196]:
class Friend(Student):
    def bonus(self):
        return self._bonus*1.12

## 3. Create a function that:
### Accepts any employee object
### Displays employee ID, salary, and calculated bonus
### Uses isinstance() to identify and display object type

In [204]:
def emp(df):
    df=df[df['EmployeeID']=='1001']
    return df

In [207]:
e=emp(df)
e.Salary

Series([], Name: Salary, dtype: int64)

## Question 7 (10 Marks)
### Write a Python program with the following requirements:
## 1. Create three separate functions:
## Function 1: Accepts keyword arguments for filtering
## Supports multiple filter conditions
## Uses conditional logic
## Returns filtered DataFrame

In [ ]:
def filter_conditions(df):
    filtered=df[

## Function 2: Groups data by department
### Uses Pandas groupby()
### Constructs dictionary with loops
### Returns department-based grouping

In [183]:
dept=df.groupby('Department')['Project_Count'].sum()
dept

Department
Engineering    1481
Finance        1609
HR             1674
Marketing      1616
Operations     1437
Sales          1307
Name: Project_Count, dtype: int64

In [188]:
def department(df):
    result={}
    for k,v in df.items():
        result={(k,v in dept)}
    return result

## Function 3: Calculates department-level statistics
### Computes count, average salary, and average performance
### Groups by department
### Returns formatted dictionary

In [208]:
count=df['Department'].count()
count

np.int64(1200)

In [210]:
avg=df['Salary'].mean()
avg

np.float64(1396182.5541666667)

In [213]:
avg=df['Performance_Rating'].mean()
avg

np.float64(3.0387333333333335)

In [216]:
df_level=df.groupby('Department')
df_level

In [229]:
lst=[1,2,3,4]

In [230]:
lst

[1, 2, 3, 4]

In [231]:
a=["abc",123]
a

['abc', 123]